#include "CoreObjectFactories.h"
#include "../OpenGLRenderer.h"

CoreObjectFactory<Trigger_2D> g_Factory_Trigger_2D;
CoreObjectFactory<ScriptObject> g_Factory_ScriptObject;
CoreObjectFactory<ObjectGroup> g_Factory_ObjectGroup;
CoreObjectFactory<SoundPlayer> g_Factory_SoundPlayer;
CoreObjectFactory<TileAffector> g_Factory_TileAffector;
CoreObjectFactory<RenderableGeometry3D> g_Factory_Geometry_Normal;
CoreObjectFactory<RenderableGeometry3D> g_Factory_Geometry_UI;
CoreObjectFactory<RenderableGeometry3D> g_Factory_Geometry_Light;
CoreObjectFactory<RenderableSceneObject3D> g_Factory_RenderableSceneObject;
CoreObjectFactory<BasicParticle_2D> g_Factory_BasicParticle_2D;
CoreObjectFactory<AnimatedParticle_2D> g_Factory_AnimatedParticle_2D;
CoreObjectFactory<MuzzleFlareParticle_2D> g_Factory_MuzzleFlareParticle_2D;
CoreObjectFactory<Spawner> g_Factory_Spawner;
CoreObjectFactory<NullObject> g_Factory_NullObject;

